spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.p6spy.engine.spy.P6SpyDriver
    url: jdbc:p6spy:mysql://localhost:3306/dcy-fast?useUnicode=true&characterEncoding=utf8&serverTimezone=GMT%2B8&allowMultiQueries=true&nullCatalogMeansCurrent=true&autoReconnect=true&failOverReadOnly=false
    username: root
    password: root
  redis:
    host: 192.168.109.132
    port: 6379
    database: 4

#文件配置fastdfs、minio
file:
  type: minio
  minio:
    url: http://192.168.109.132:81
    access-key: minio
    secret-key: minio123
    bucket: test
    web-url: http://192.168.109.132:81/${file.minio.bucket}/


#fdfs:
#  web-server-url: http://192.168.109.132:8888
#  tracker-list: 192.168.109.132:22122